use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn collect_rs_files(root: &Path, files: &mut Vec<PathBuf>) {
    if let Ok(entries) = fs::read_dir(root) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_rs_files(&path, files);
            } else if path.extension().and_then(|ext| ext.to_str()) == Some("rs") {
                files.push(path);
            }
        }
    }
}

fn to_module_name(path: &Path) -> String {
    path.to_string_lossy()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

fn generate_backend_contract_modules() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let backend_tests_dir = manifest_dir.join("../tests/backend");

    println!("cargo:rerun-if-changed={}", backend_tests_dir.display());

    let mut files = Vec::new();
    collect_rs_files(&backend_tests_dir, &mut files);
    files.sort();

    for file in &files {
        println!("cargo:rerun-if-changed={}", file.display());
    }

    let mut generated = String::from("// @generated by src-tauri/build.rs\n");

    for file in files {
        let module_name = format!("backend_contract_{}", to_module_name(&file));
        generated.push_str(&format!(
            "#[path = r#\"{}\"#]\nmod {};\n\n",
            file.display(), module_name
        ));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_file = out_dir.join("backend_contract_modules.rs");
    fs::write(out_file, generated).expect("write generated backend contract modules");
}

fn main() {
    generate_backend_contract_modules();
    tauri_build::build()
}
