[build]
target = "./index.html"

[watch]
ignore = [
    "./.git",
    "./crates",
    "./dist",
    "./node_modules",
    "./src-tauri",
    "./styles.css",
    "./target",
]

[serve]
port = 1420
open = false
